package tools

import (
	"code-agent/internal/assetref"
	"code-agent/internal/sessionfork"
	"context"
	"encoding/json"
	"time"
)

// ExecutionContext carries the runtime state for a single tool execution.
// It is a value type — tools receive it by value and must not mutate it.
// All fields are immutable for the duration of the Execute call.
type ExecutionContext struct {
	// WorkspaceRoot is the absolute path of the project root directory.
	// Tools use it to resolve relative paths and enforce workspace boundaries.
	WorkspaceRoot string

	// SessionID is the stable conversation identifier (the session UUID).
	SessionID string

	// TurnID is the per-turn identifier (e.g. "turn_5").
	TurnID string

	// CallID is the per-tool-call identifier (e.g. "call_3").
	CallID string

	// ExecutionID identifies the model invocation that requested this tool call.
	// Managed tools forward it to Gateway for end-to-end correlation.
	ExecutionID string

	// RequestID is the client-generated turn correlation key.
	RequestID string

	// PlanMode is true when the runner is in a planning/proposing state.
	// Tools that need different behavior during plan mode (e.g. write_file
	// restricting writes to .codeagent/plans/) check this field.
	PlanMode bool

	// PathAccessApprover gates read-only access to paths outside the workspace.
	// When non-nil, read tools (read_file, list_files, grep) request approval for
	// external paths instead of hard-rejecting them. When nil (headless mode,
	// legacy clients), external access is denied with a "path escapes workspace"
	// error — the existing behaviour is unchanged.
	//
	// Write and shell tools must NOT consult this field; they are always gated
	// by the side-effecting Approver chain and must reject external paths.
	PathAccessApprover PathAccessApprover

	// OnStdout, if set, receives stdout chunks as the command produces them.
	// Tools that support streaming call this during execution; nil-safe.
	OnStdout func(chunk string)
	// OnStderr, if set, receives stderr chunks as the command produces them.
	// Tools that support streaming call this during execution; nil-safe.
	OnStderr func(chunk string)

	// NestedExecutor runs a tool selected by an embedded deterministic
	// workflow. It preserves the same approval, inspection, client-dispatch and
	// lifecycle rules as an ordinary Agent tool call. Nil means nested tool
	// execution is unavailable in this host.
	NestedExecutor NestedToolExecutor

	// OnWorkflowEvent publishes structured progress from an embedded workflow
	// into the parent Agent event stream.
	OnWorkflowEvent func(kind string, payload json.RawMessage)

	// WorkflowPlanApproval blocks until the user approves or rejects the DAG
	// generated by plan_workflow. content carries the DAG JSON. The call
	// blocks synchronously (same pattern as the per-tool Approver). Nil or
	// auto-approves when not set (test/headless path).
	WorkflowPlanApproval func(planID, title, content string) bool

	// ToolRegistry is the current turn-local registry, including workspace MCP
	// and session-scoped client tools.
	ToolRegistry *Registry

	// Model is the parent turn's resolved model name. The task subagent reads
	// this to populate its own model when the frozen config has an empty model
	// field (as Gateway does — the server chooses the model per-turn). Without
	// it, an empty model reaches the Gateway API, which rejects the request
	// with "400 Model field required" for new sessions.
	Model string

	// SessionIndex provides cross-workspace session discovery and read access.
	// It is the tool-layer interface to the global index.db. Nil means
	// cross-session tools (list_sessions, read_session) are unavailable.
	SessionIndex SessionIndex

	// SessionControl routes cross-session work through the target Runtime owner.
	// Nil means control primitives are unavailable in this host.
	SessionControl SessionControl
}

type SessionControl interface {
	Send(context.Context, SessionSendRequest) (SessionDelivery, error)
	WaitAny(context.Context, []SessionWaitTarget, time.Duration) (SessionWaitResult, error)
	PollTurn(context.Context, string, string, int64) (*SessionWaitCompletion, int64, error)
	CreateSession(context.Context, SessionCreateRequest) (SessionSpawnResult, error)
	sessionfork.Service
}

type SessionCreateRequest struct {
	ParentSessionID string
	ParentTurnID    string
	RequestID       string
	WorkspacePath   string
	Name            string
	ExecutionPolicy string
	WorktreeName    string
	BaseRef         string
}

type SessionSpawnResult struct {
	ID              string `json:"id"`
	ParentSessionID string `json:"parent_session_id"`
	SourceSessionID string `json:"source_session_id,omitempty"`
	WorkspacePath   string `json:"workspace_path"`
	Kind            string `json:"kind"`
	Status          string `json:"status"`
}

type SessionSendRequest struct {
	TargetSessionID string
	Message         string
	Model           string
	SenderSessionID string
	SenderTurnID    string
	MessageID       string
	CorrelationID   string
	Intent          string
}

type SessionDelivery struct {
	Accepted  bool   `json:"accepted"`
	Delivery  string `json:"delivery"`
	SessionID string `json:"session_id"`
	TurnID    string `json:"turn_id"`
	Cursor    int64  `json:"cursor"`
}

type SessionWaitTarget struct {
	SessionID string `json:"id"`
	TurnID    string `json:"turn_id"`
	Cursor    int64  `json:"cursor"`
}

type SessionWaitCompletion struct {
	SessionID string          `json:"id"`
	TurnID    string          `json:"turn_id"`
	Status    string          `json:"status"`
	Cursor    int64           `json:"cursor"`
	Event     json.RawMessage `json:"event,omitempty"`
}

type SessionWaitResult struct {
	Completed []SessionWaitCompletion `json:"completed"`
	Waiting   []SessionWaitTarget     `json:"waiting"`
	TimedOut  bool                    `json:"timed_out"`
}

// SessionIndex is the cross-workspace session discovery interface consumed
// by list_sessions and read_session. Implementations are backed by index.db
// plus the per-workspace session stores.
type SessionIndex interface {
	// ListAll returns every session recorded in the index, newest first.
	ListAll() ([]SessionIndexEntry, error)
	// Get returns the index entry for a single session, or nil if not found.
	Get(id string) (*SessionIndexEntry, error)
	// Read returns metadata and a last-turn summary for a session by loading
	// it from its per-workspace store. Returns nil if not found.
	Read(ctx context.Context, id string) (*SessionIndexDetail, error)
}

// SessionIndexEntry is one row from the cross-workspace session index.
type SessionIndexEntry struct {
	ID            string `json:"id"`
	WorkspacePath string `json:"workspace_path"`
	Name          string `json:"name"`
	Model         string `json:"model"`
	TurnStatus    string `json:"turn_status"`
	MessageCount  int    `json:"message_count"`
	PromptTokens  int    `json:"prompt_tokens"`
	UpdatedAt     string `json:"updated_at"`
	ArchivedAt    string `json:"archived_at,omitempty"`
}

// SessionIndexDetail is the full metadata + summary returned by Read.
type SessionIndexDetail struct {
	ID            string `json:"id"`
	WorkspacePath string `json:"workspace_path"`
	Name          string `json:"name"`
	Model         string `json:"model"`
	TurnStatus    string `json:"turn_status"`
	MessageCount  int    `json:"message_count"`
	PromptTokens  int    `json:"prompt_tokens"`
	Summary       string `json:"summary"`
	LastTurn      string `json:"last_turn"`
	LastTurnID    string `json:"last_turn_id,omitempty"`
	LastUserInput string `json:"last_user_input,omitempty"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

// NestedToolExecutor is the controlled re-entry point used by embedded
// workflow engines. nestedCallID must be stable for the workflow node attempt.
type NestedToolExecutor interface {
	ExecuteNestedTool(
		ctx context.Context,
		parentCallID string,
		nestedCallID string,
		tool Tool,
		input json.RawMessage,
	) (ToolResult, error)
}

// PathAccessApprover gates read-only access to paths outside the workspace
// boundary. It is intentionally narrow — it only answers "may we read this
// external path?" and does not cover side-effecting operations (those go through
// the full agent.Approver chain).
//
// Implementations may be synchronous (a channel-backed RemoteApprover) or
// asynchronous (a Policy that auto-allows known-safe directories). A nil
// PathAccessApprover is fail-safe: external paths are rejected.
type PathAccessApprover interface {
	// ApproveExternalPath asks whether a read-only operation may proceed on a
	// path that has been classified as outside the workspace. operation is
	// "read" for read_file and grep, "list" for list_files.
	// Return true to allow, false to deny.
	ApproveExternalPath(absolutePath string, operation string) bool
}

type ToolResult struct {
	Content string          `json:"content"`
	Output  json.RawMessage `json:"output,omitempty"`
	Assets  []assets.Ref    `json:"assets,omitempty"`
	// Usage is populated by billable managed tools. Local tools leave it nil.
	// It is an event side-channel and is not included in the model observation.
	Usage *ToolUsage `json:"usage,omitempty"`
	// ModelUsage is model work performed inside a composite tool, such as Flux
	// DAG generation/repair. The Runner folds it into ModelBillingUnits.
	ModelUsage *ModelUsage `json:"model_usage,omitempty"`
	// NestedUsages are managed-tool receipts produced by workflow nodes.
	NestedUsages []*ToolUsage `json:"nested_usages,omitempty"`
}

type ModelUsage struct {
	PromptTokens       int   `json:"prompt_tokens"`
	CompletionTokens   int   `json:"completion_tokens"`
	TotalTokens        int   `json:"total_tokens"`
	BillingUnits       int64 `json:"billing_units"`
	CachedPromptTokens int   `json:"cached_prompt_tokens,omitempty"`
}

// ToolUsage is the provider-neutral billing receipt returned by a managed tool.
// BillingUnits contributes to the user's unified Usage Units; provider credits
// remain diagnostic/provider accounting and never replace BillingUnits.
type ToolUsage struct {
	ToolCallID      string `json:"tool_call_id"`
	ToolName        string `json:"tool_name"`
	Provider        string `json:"provider"`
	Operation       string `json:"operation"`
	ProviderCredits int64  `json:"provider_credits"`
	BillingUnits    int64  `json:"billing_units"`
	FundingSource   string `json:"funding_source"`
	ReservationID   string `json:"reservation_id"`
	PricingVersion  int    `json:"pricing_version"`
	Replayed        bool   `json:"replayed,omitempty"`
}

// TurnFatalToolError marks a tool failure that must stop the turn after the
// tool-result message has been committed. Authentication and quota failures use
// this path so the host receives auth_expired/quota_exceeded instead of the
// model merely seeing a retryable-looking "Tool error" observation.
type TurnFatalToolError interface {
	error
	TurnFatalToolError() bool
}

// ClientProxyTool is a Tool stub registered from a client's register_tools
// message. It provides the tool definition to the model (Name, Description,
// InputSchema) so the model can call it, but Execute is never invoked — the
// agent loop sees ExecStrictClient and delegates to the remote client instead.
type ClientProxyTool struct {
	name        string
	description string
	inputSchema json.RawMessage
}

// NewClientProxyTool creates a client-tool proxy from a wire definition.
func NewClientProxyTool(name, description string, inputSchema json.RawMessage) *ClientProxyTool {
	return &ClientProxyTool{name: name, description: description, inputSchema: inputSchema}
}

func (t *ClientProxyTool) Name() string                 { return t.name }
func (t *ClientProxyTool) Description() string          { return t.description }
func (t *ClientProxyTool) InputSchema() json.RawMessage { return t.inputSchema }
func (t *ClientProxyTool) ExecutionMode() ExecutionMode { return ExecStrictClient }

// Execute is a no-op stub. The agent loop never calls it for ExecStrictClient tools.
func (t *ClientProxyTool) Execute(_ context.Context, _ ExecutionContext, _ json.RawMessage) (ToolResult, error) {
	return ToolResult{Content: "tool error: this tool runs on the client"}, nil
}

// compile-time checks
var _ Tool = (*ClientProxyTool)(nil)
var _ ClientTool = (*ClientProxyTool)(nil)

// ExecutionMode declares which side must execute a tool. This is a contract —
// not a suggestion. The server loop and client dispatcher both consult it to
// make non-negotiable decisions about who runs the tool.
//
// See docs/protocols/agent-wire-v1.1-client-tool-execution.md §2.
type ExecutionMode string

const (
	// ExecStrictServer: only the server may execute this tool (grep, git, bash, …).
	ExecStrictServer ExecutionMode = "strict_server"

	// ExecStrictClient: only the client may execute this tool (AVFoundation,
	// HealthKit, Photos, …). The server physically cannot run these.
	ExecStrictClient ExecutionMode = "strict_client"

	// ExecFlex: either side can execute; the server does by default. v2 may
	// negotiate. web_search, web_fetch fall here.
	ExecFlex ExecutionMode = "flex"
)

// ClientTool is an optional interface a tool implements to declare that it must
// be executed by the client. Tools that don't implement it default to
// ExecStrictServer.
type ClientTool interface {
	ExecutionMode() ExecutionMode
}

type Tool interface {
	Name() string
	Description() string
	InputSchema() json.RawMessage
	Execute(ctx context.Context, ec ExecutionContext, input json.RawMessage) (ToolResult, error)
}

// OutputSchemaProvider is an optional interface for tools that expose a
// structured output schema. Flux tool adapters use it to populate per-tool
// OutputSchema instead of the generic {content, output, assets} fallback.
type OutputSchemaProvider interface {
	OutputSchema() json.RawMessage
}
